/*

OPENAI CHATGPT PROMPTS:

Please flatten and alphabetize the following array, then display it
in plain text:
* flatten opposites, then in new chat window paste flat list

...

I would like you to go through each tarot card in the major arcana.
Using ONLY the provided list, go through each word and filter out any
that do not apply to the current card. Take the remaining words and
assign them as an array to the card's name in a JSON object. Do not
use the word "The" or any numbers in the card's name. It is important
that each array only has words from the provided list. Please do not
provide any synonyms, do not change the word's grammar or tense, and
do not draw words for the cards from other sources.

...

Remember, by provided list I mean the list I first pasted into the chat.
You seem to be straying from the list. Please only use those words, and
no synonyms. Give it another try.

...

Can you do the same thing for the [SUIT] suit of the minor arcana?
Please write the card names with digits instead of spelling out numbers.

...

* I ended up with words from outside the list on my final try, but I
* don't mind it. I think they work, and each card should have at least
* a few words from the opposites list. Lesson: Chat GPT can be finicky.

* 9/20/23: adding words and opposites from old Tarot project

*/

const opposites = [
    ["abundance", "scarcity"],
    ["acceleration", ""],
    ["accomplishment", "failure"],
    ["action", "complacent"],
    ["action", "inaction"],
    ["action", "waiting"],
    ["active", "passive"],
    ["active", "yin"],
    ["adaptability", ""],
    ["agreement", "conflict"],
    ["ambition", "complacency"],
    ["anxiety", "contentment"],
    ["apathy", "curiosity"],
    ["apathy", "emotion"],
    ["arrival", "departure"],
    ["balance", "chaos"],
    ["balance", "imbalance"],
    ["beginning", "ending"],
    ["beginnings", "endings"],
    ["belief", "loss of faith"],
    ["betrayal", "loyalty"],
    ["blindness", "foresight"],
    ["bondage", "freedom"],
    ["boundaries", "unrestricted"],
    ["bravery", "fear"],
    ["breakthrough", "stagnation"],
    ["burden", "lightness"],
    ["calm", "shock"],
    ["carelessness", "responsibility"],
    ["celebration", "mourning"],
    ["challenges", "ease"],
    ["change", "stability"],
    ["chaos", "control"],
    ["chaos", "peace"],
    ["chaos", "serenity"],
    ["charisma", "dullness"],
    ["charm", "repulsion"],
    ["charming", "repulsive"],
    ["clarity", "confusion"],
    ["clarity", "mystery"],
    ["cold", "warmth"],
    ["collaboration", "solitude"],
    ["companionship", "solitude"],
    ["compassion", "cruelty"],
    ["competition", "cooperation"],
    ["completion", "incompletion"],
    ["conformity", "individuality"],
    ["conformity", "rebellion"],
    ["confusion", "guidance"],
    ["connection", "disconnection"],
    ["conscious mind", "unconscious mind"],
    ["contentment", "dissatisfaction"],
    ["contraction", "expansion"],
    ["control", "loss of control"],
    ["courage", "fear"],
    ["creative", "uncreative"],
    ["creativity", "uncreativity"],
    ["deadlock", "movement"],
    ["deception", "honesty"],
    ["decision", "indecision"],
    ["defeat", "victory"],
    ["dependence", "independence"],
    ["dependency", "self-sufficiency"],
    ["desengagement", "engagement"],
    ["desire", "disinterest"],
    ["destiny", "randomness"],
    ["deterioration", "renewal"],
    ["determination", "hesitation"],
    ["diligence", "neglect"],
    ["direct", "indirect"],
    ["disappointment", "satisfaction"],
    ["discord", "harmony"],
    ["dishonesty", "honesty"],
    ["dissatisfaction", "joy"],
    ["dissonance", "harmony"],
    ["division", "unity"],
    ["drama", "peace"],
    ["dream", "nightmare"],
    ["dreams", "reality"],
    ["ease", "effort"],
    ["ease", "hardship"],
    ["emotional", "unemotional"],
    ["emptiness", "fulfillment"],
    ["engagement", "withdrawal"],
    ["enlightenment", "ignorance"],
    ["equity", "injustice"],
    ["expansion", "restriction"],
    ["experience", "inexperience"],
    ["failure", "success"],
    ["fairness", "unfairness"],
    ["faith", "loss of faith"],
    ["falsehood", "truth"],
    ["fate", "free will"],
    ["feeling", "numbness"],
    ["femininity", "masculinity"],
    ["flexibility", "rigidity"],
    ["followership", "leadership"],
    ["fortitude", "weakness"],
    ["forward-looking", "nostalgia"],
    ["fragility", "resilience"],
    ["freedom", "imprisonment"],
    ["frigidity", "sensuality"],
    ["gain", "loss"],
    ["generosity", "greed"],
    ["generosity", "possessiveness"],
    ["generosity", "selfishness"],
    ["grief", "happiness"],
    ["happiness", "heartbreak"],
    ["happiness", "sadness"],
    ["hatred", "love"],
    ["healing", "hurt"],
    ["healthy", "weak"],
    ["hope", "hopelessness"],
    ["ignorance", "inquiry"],
    ["illness", "recovery"],
    ["illusion", "reality"],
    ["impatience", "patience"],
    ["improvisation", "planning"],
    ["incompetence", "mastery"],
    ["indifference", "interest"],
    ["indifference", "passion"],
    ["innovation", "tradition"],
    ["insecurity", "security"],
    ["inspiration", "uninspired"],
    ["intuition", "reason"],
    ["irrationality", "rationality"],
    ["irresponsibility", "responsibility"],
    ["isolation", "togetherness"],
    ["journey", "staying put"],
    ["joy", "sorrow"],
    ["justice", "unfairness"],
    ["laziness", "work"],
    ["lethargy", "vitality"],
    ["luck", "misfortune"],
    ["materialism", "spirituality"],
    ["maternal", "paternal"],
    ["movement", "stagnation"],
    ["narrowness", "perspective"],
    ["negative", "positive"],
    ["neglect", "nurturing"],
    ["new", "old"],
    ["nonphysical conquest", "physical conquest"],
    ["obscurity", "recognition"],
    ["optimism", "pessimism"],
    ["pain", "pleasure"],
    ["passive", "yang"],
    ["peace", "struggle"],
    ["poverty", "prosperity"],
    ["poverty", "wealth"],
    ["power", "weakness"],
    ["predictability", "spontaneity"],
    ["relationship", "solitude"],
    ["resistance", "surrender"],
    ["resistance", "temptation"],
    ["revelation", "secrecy"],
    ["risk", "safety"],
    ["secrets", "transparency"],
    ["self-confidence", "self-doubt"],
    ["serenity", "struggle"],
    ["sleep", "sleeplessness"],
    ["stability", "upheaval"],
    ["stagnation", "transformation"],
    ["strength", "weakness"],
    ["thrift", "waste"],
    ["tranquility", "worry"],
    ["yang", "yin"],
];

const allCards = {
    Fool: [
        "beginning",
        "beginnings",
        "carelessness",
        "creativity",
        "curiosity",
        "freedom",
        "ignorance",
        "inexperience",
        "innocence",
        "innovation",
        "new choice",
        "potential",
        "spontaneity",
    ],
    Magician: [
        "ability",
        "action",
        "active",
        "adaption",
        "concentration",
        "confidence",
        "conscious mind",
        "control",
        "creative",
        "innovation",
        "inspiration",
        "power",
        "skill",
        "talent",
        "transformation",
        "yang",
    ],
    "High Priestess": [
        "intuition",
        "meditation",
        "mystery",
        "passive",
        "potential",
        "reflection",
        "secrecy",
        "secret",
        "secrets",
        "solitude",
        "spiritual connection",
        "tranquility",
        "unconscious mind",
        "yin",
    ],
    Empress: [
        "abundance",
        "beauty",
        "creativity",
        "desire",
        "femininity",
        "fertility",
        "gentleness",
        "love",
        "material world",
        "maternal",
        "nature",
        "nurturing",
        "pleasure",
        "protection",
    ],
    Emperor: [
        "authority",
        "control",
        "determination",
        "experience",
        "hierarchy",
        "leadership",
        "masculinity",
        "paternal",
        "power",
        "rationality",
        "regulation",
        "responsibility",
        "rule",
        "stability",
        "strength",
        "structure",
    ],
    Hierophant: [
        "belief",
        "conformity",
        "education",
        "faith",
        "group",
        "guidance",
        "hierarchy",
        "initiation",
        "institution",
        "knowledge",
        "ritual",
        "spiritual connection",
        "spirituality",
        "teaching",
        "tradition",
        "unity",
    ],
    Lovers: [
        "choice",
        "connection",
        "desire",
        "harmony",
        "intimacy",
        "love",
        "passion",
        "pleasure",
        "relationship",
        "self-confidence",
        "sex",
        "union",
    ],
    Chariot: [
        "assertion",
        "bravery",
        "control",
        "courage",
        "determination",
        "emotional discipline",
        "movement",
        "physical conquest",
        "success",
        "traveling",
        "victory",
        "willpower",
    ],
    Strength: [
        "bravery",
        "caring",
        "composure",
        "confidence",
        "courage",
        "determination",
        "endurance",
        "energy",
        "fortitude of character",
        "gentleness",
        "health",
        "nonphysical conquest",
        "patience",
        "power",
        "strength",
        "vitality",
    ],
    Hermit: [
        "contemplation",
        "enlightenment",
        "guidance",
        "introspection",
        "isolation",
        "meditation",
        "patience",
        "reflection",
        "searching",
        "self-sufficiency",
        "solitude",
        "wisdom",
    ],
    "Wheel of Fortune": [
        "change",
        "cycle",
        "destiny",
        "fate",
        "luck",
        "movement",
        "opportunity",
        "potential",
        "randomness",
        "transition",
        "turning point",
        "unstoppable change",
        "vision",
    ],
    Justice: [
        "balance",
        "cause-and-effect",
        "clarity",
        "decision",
        "equity",
        "fairness",
        "honesty",
        "justice",
        "rationality",
        "reflection",
        "responsibility",
        "rule",
        "truth",
    ],
    "Hanged Man": [
        "acceptance",
        "altered perspective",
        "change",
        "meditation",
        "perspective",
        "punishment",
        "reflection",
        "release",
        "restriction",
        "sacrifice",
        "surrender",
        "suspense",
        "transformation",
        "upside-down",
        "wait",
        "waiting",
    ],
    Death: [
        "change",
        "dramatic transformation",
        "elimination",
        "ending",
        "endings",
        "lifestyle change",
        "loss",
        "mystery",
        "release",
        "renewal",
        "transformation",
        "transition",
        "turning point",
        "unstoppable change",
    ],
    Temperance: [
        "adaptability",
        "adaptation",
        "balance",
        "combination",
        "compromise",
        "cooperation",
        "harmony",
        "healing",
        "health",
        "integration",
        "moderation",
        "patience",
    ],
    Devil: [
        "bondage",
        "deception",
        "desire",
        "greed",
        "hedonism",
        "hopelessness",
        "ignorance",
        "illusion",
        "loss of control",
        "loss of faith",
        "materialism",
        "selfishness",
        "temptation",
        "weakness",
    ],
    Tower: [
        "change",
        "chaos",
        "crisis",
        "disaster",
        "disruption",
        "humbling experience",
        "punishment",
        "release",
        "revelation",
        "separation",
        "sudden change",
        "transformation",
        "upheaval",
    ],
    Star: [
        "beauty",
        "clarity",
        "faith",
        "generosity",
        "guidance",
        "healing",
        "hope",
        "illumination",
        "inspiration",
        "peace",
        "reflection",
        "renewal",
        "serenity",
        "vitality",
    ],
    Moon: [
        "confusion",
        "deception",
        "dream",
        "emotional",
        "fear",
        "illusion",
        "imagination",
        "intuition",
        "magnetism",
        "mystery",
        "reflection",
        "secrets",
        "strangeness",
        "unconscious mind",
    ],
    Sun: [
        "assurance",
        "bliss",
        "brightness",
        "celebration",
        "clarity",
        "energy",
        "enlightenment",
        "generosity",
        "greatness",
        "growth",
        "happiness",
        "illumination",
        "joy",
        "positivity",
        "success",
        "vitality",
        "warmth",
    ],
    Judgement: [
        "absolution",
        "awakening",
        "cause-and-effect",
        "forgiveness",
        "recognition",
        "reflection",
        "release",
        "renewal",
        "revelation",
        "sense of purpose",
        "spiritual rebirth",
        "transformation",
    ],
    World: [
        "accomplishment",
        "achievement",
        "completion",
        "ending",
        "enlightenment",
        "freedom",
        "fulfillment",
        "integration",
        "promotion",
        "success",
        "unity",
        "wholeness",
    ],
    "Ace of Wands": [
        "adventure",
        "beginning",
        "beginnings",
        "creative urge",
        "creativity",
        "desire",
        "energy",
        "enterprise",
        "inspiration",
        "intellect",
        "originality",
        "passion",
        "phallic",
        "potency",
        "potential",
        "strength",
        "vision",
    ],
    "2 of Wands": [
        "ambition",
        "appetite",
        "arrogance",
        "balance",
        "choice",
        "curiosity",
        "decision",
        "design",
        "desire",
        "direction",
        "drive",
        "duality",
        "energy",
        "enthusiasm",
        "expectation",
        "exploration",
        "force",
        "foresight",
        "lust",
        "plan",
        "planning",
        "progress",
        "project",
        "restlessness",
        "risk",
        "search",
        "thirst",
        "yearning",
    ],
    "3 of Wands": [
        "action",
        "anticipation",
        "assistance",
        "attention",
        "business",
        "care",
        "community",
        "concept",
        "contemplation",
        "creativity",
        "effort",
        "expansion",
        "exploration",
        "flux",
        "foresight",
        "growth",
        "help",
        "hope",
        "motion",
        "observation",
        "opportunity",
        "optimism",
        "outcome",
        "patience",
        "preparation",
        "prosperity",
        "trade",
        "wait",
    ],
    "4 of Wands": [
        "achievement",
        "blessing",
        "celebration",
        "completion",
        "domestic bliss",
        "expansion",
        "freedom",
        "happiness",
        "harmony",
        "joy",
        "outcome",
        "peace",
        "possession",
        "prosperity",
        "serenity",
        "stability",
        "unity",
    ],
    "5 of Wands": [
        "action",
        "adversity",
        "challenge",
        "change",
        "chaos",
        "competition",
        "conflict",
        "effort",
        "energy",
        "game",
        "imitation",
        "restriction",
        "rivalry",
        "strife",
        "struggle",
        "training",
    ],
    "6 of Wands": [
        "accomplishment",
        "achievement",
        "announcement",
        "arrival",
        "award",
        "balance",
        "confidence",
        "fame",
        "growth",
        "harmony",
        "illumination",
        "journey",
        "message",
        "parade",
        "pride",
        "publicity",
        "recognition",
        "success",
        "triumph",
        "victory",
    ],
    "7 of Wands": [
        "challenge",
        "challenges",
        "competition",
        "confidence",
        "courage",
        "creativity",
        "defense",
        "determination",
        "faith",
        "fight",
        "inspiration",
        "negotiation",
        "nonconformity",
        "opinion",
        "opposition",
        "perseverance",
        "resistance",
        "self-confidence",
        "struggle",
        "willpower",
    ],
    "8 of Wands": [
        "action",
        "alliance",
        "announcement",
        "change",
        "climax",
        "communication",
        "decision",
        "logic",
        "message",
        "movement",
        "option",
        "progress",
        "reaction",
        "speed",
        "strength",
        "travel",
        "traveling",
    ],
    "9 of Wands": [
        "adventure",
        "arrival",
        "caution",
        "defense",
        "determination",
        "endurance",
        "experience",
        "fruition",
        "fulfillment",
        "guard",
        "integration",
        "obstacle",
        "opposition",
        "perseverance",
        "potential",
        "rationality",
        "resilience",
        "risk",
        "strength",
        "threshold",
        "transformation",
        "vigilance",
        "work",
    ],
    "10 of Wands": [
        "burden",
        "challenge",
        "completion",
        "culmination",
        "ending",
        "exhaustion",
        "hard work",
        "manifestation",
        "overwhelm",
        "overwhelming",
        "pressure",
        "responsibility",
        "strength",
        "struggle",
        "work",
    ],
    "Page of Wands": [
        "adventure",
        "candid",
        "commitment",
        "creativity",
        "curiosity",
        "enthusiasm",
        "exploration",
        "friendship",
        "impetuous",
        "insight",
        "inspiration",
        "learning",
        "love",
        "loyalty",
        "playful",
        "support",
        "travel",
        "vitality",
    ],
    "Knight of Wands": [
        "action",
        "adventure",
        "ambition",
        "capability",
        "chivalry",
        "courage",
        "daring",
        "determination",
        "enterprising",
        "enthusiasm",
        "exploration",
        "foresight",
        "formation",
        "idealism",
        "impatience",
        "impetuous",
        "intellect",
        "opportunity",
        "optimism",
        "passion",
        "travel",
    ],
    "Queen of Wands": [
        "autonomy",
        "charisma",
        "concept",
        "confidence",
        "determination",
        "dignity",
        "dominance",
        "exuberance",
        "independence",
        "influence",
        "leadership",
        "passion",
        "power",
        "satisfaction",
        "self-confidence",
        "strength",
    ],
    "King of Wands": [
        "ambition",
        "assertiveness",
        "authority",
        "bold",
        "boss",
        "confidence",
        "courageous",
        "creative urge",
        "dominance",
        "entrepreneur",
        "experience",
        "explosive",
        "initiative",
        "inspiration",
        "inspiring",
        "leadership",
        "motivator",
        "persuasive",
        "respect",
        "security",
        "stability",
        "strength",
        "vision",
    ],
    "Ace of Cups": [
        "abundance",
        "adaptation",
        "beginning",
        "beginnings",
        "care",
        "compassion",
        "creative urge",
        "deluge",
        "emotion",
        "emotional",
        "feeling",
        "fertility",
        "healing",
        "intuition",
        "joy",
        "love",
        "memory",
        "openness",
        "opportunity",
        "potential",
        "purification",
        "romance",
        "unconscious mind",
    ],
    "2 of Cups": [
        "agreement",
        "attraction",
        "balance",
        "connection",
        "decision",
        "duality",
        "force",
        "friendship",
        "harmony",
        "joy",
        "love",
        "marriage",
        "partnership",
        "passion",
        "relationship",
        "sympathy",
        "understanding",
        "union",
        "unity",
    ],
    "3 of Cups": [
        "birth",
        "celebration",
        "collaboration",
        "comfort",
        "communion",
        "community",
        "concept",
        "dance",
        "excitement",
        "feast",
        "flux",
        "friendship",
        "gathering",
        "happiness",
        "health",
        "intoxication",
        "joy",
        "outcome",
        "relief",
        "reunion",
        "sharing",
        "teamwork",
        "victory",
        "work",
    ],
    "4 of Cups": [
        "apathy",
        "boredom",
        "complacency",
        "contemplation",
        "disappointment",
        "discontent",
        "discouragement",
        "disdain",
        "dissatisfaction",
        "distraction",
        "emotional",
        "expansion",
        "expectation",
        "habit",
        "introspection",
        "missed opportunities",
        "nausea",
        "outcome",
        "possession",
        "reflection",
        "refusal",
        "stability",
    ],
    "5 of Cups": [
        "addiction",
        "adversity",
        "bereavement",
        "change",
        "despair",
        "difficulty",
        "disappointment",
        "emotional",
        "fear",
        "grief",
        "guilt",
        "loss",
        "pessimism",
        "reflection",
        "refusal",
        "regret",
        "restriction",
        "sacrifice",
        "sadness",
        "shortage",
        "sorrow",
        "vanity",
    ],
    "6 of Cups": [
        "balance",
        "childhood",
        "connection",
        "endowment",
        "exchange",
        "friendship",
        "gift",
        "growth",
        "hearth",
        "home",
        "illumination",
        "innocence",
        "journey",
        "joy",
        "memories",
        "message",
        "nostalgia",
        "offer",
        "passion",
        "past",
        "peace",
        "remembrance",
        "reminiscing",
        "romance",
        "safety",
        "sentiment",
        "sharing",
        "yearning",
    ],
    "7 of Cups": [
        "challenge",
        "choice",
        "choices",
        "confusion",
        "creativity",
        "deception",
        "desire",
        "dream",
        "dreams",
        "faith",
        "fantasy",
        "illusion",
        "imagination",
        "indecision",
        "option",
        "selection",
        "temptation",
        "variety",
        "vision",
        "willpower",
    ],
    "8 of Cups": [
        "adventure",
        "change",
        "departure",
        "emotional",
        "escapism",
        "exploration",
        "freedom",
        "journey",
        "logic",
        "loneliness",
        "movement",
        "moving on",
        "progress",
        "rejection",
        "renunciation",
        "restart",
        "search",
        "shyness",
        "strength",
        "transition",
        "travel",
    ],
    "9 of Cups": [
        "abundance",
        "admiration",
        "affection",
        "contentment",
        "fruition",
        "fulfillment",
        "happiness",
        "joy",
        "pleasure",
        "potential",
        "satisfaction",
        "sensuality",
        "success",
        "transformation",
        "virtue",
        "wish fulfillment",
        "yes",
    ],
    "10 of Cups": [
        "celebration",
        "commitment",
        "community",
        "completion",
        "contentment",
        "culmination",
        "emotional",
        "ending",
        "family",
        "friendship",
        "fulfillment",
        "happiness",
        "harmony",
        "joy",
        "manifestation",
        "peace",
        "rest",
        "success",
    ],
    "Page of Cups": [
        "compassion",
        "contemplation",
        "creativity",
        "curiosity",
        "devotion",
        "dreams",
        "emotion",
        "emotional",
        "enthusiasm",
        "friendship",
        "gentle",
        "grace",
        "idea",
        "insight",
        "inspiration",
        "instinct",
        "intuition",
        "joy",
        "openness",
        "perception",
        "potential",
        "presence",
        "receptivity",
        "romance",
        "sensitivity",
        "sweetness",
        "synchronicity",
    ],
    "Knight of Cups": [
        "action",
        "charm",
        "compassion",
        "creativity",
        "determination",
        "dreamer",
        "emotion",
        "emotional",
        "encouragement",
        "flattery",
        "formation",
        "ideal",
        "idealism",
        "imagination",
        "insight",
        "inspiration",
        "introspection",
        "opportunity",
        "pleasure",
        "reflection",
        "romance",
        "seduction",
        "sensitivity",
        "temperamental",
        "warmth",
    ],
    "Queen of Cups": [
        "affection",
        "attraction",
        "charm",
        "compassion",
        "concept",
        "emotion",
        "emotional",
        "empathy",
        "friend",
        "influence",
        "intuition",
        "kindness",
        "listening",
        "love",
        "mystery",
        "nurturing",
        "reflection",
        "responsive",
        "satisfaction",
        "sensitivity",
        "support",
        "sweetness",
        "sympathy",
        "tranquility",
        "understanding",
        "warmth",
    ],
    "King of Cups": [
        "affection",
        "attraction",
        "authority",
        "balance",
        "calmness",
        "charm",
        "chivalry",
        "compassion",
        "composure",
        "cooperation",
        "creative urge",
        "culture",
        "emotional",
        "empathy",
        "grace",
        "intuition",
        "joy",
        "leadership",
        "love",
        "loyalty",
        "protection",
        "stability",
        "subtlety",
        "sympathy",
        "wisdom",
    ],
    "Ace of Swords": [
        "accomplishment",
        "accountability",
        "anger",
        "beginning",
        "beginnings",
        "clarity",
        "creative urge",
        "determination",
        "focus",
        "insight",
        "intellect",
        "mental",
        "potential",
        "responsibility",
        "retribution",
        "truth",
    ],
    "2 of Swords": [
        "adaptation",
        "adjustment",
        "balance",
        "blindness",
        "blockage",
        "choice",
        "choices",
        "compromise",
        "contemplation",
        "decision",
        "denial",
        "dilemma",
        "duality",
        "duel",
        "force",
        "grace",
        "indecision",
        "meditation",
        "reflection",
        "stalemate",
        "subtlety",
        "tension",
    ],
    "3 of Swords": [
        "betrayal",
        "community",
        "concept",
        "emotional",
        "flux",
        "grief",
        "guilt",
        "heartbreak",
        "injury",
        "loneliness",
        "loss",
        "meditation",
        "outcome",
        "pain",
        "regret",
        "rejection",
        "sadness",
        "separation",
        "sorrow",
        "suffering",
        "treason",
    ],
    "4 of Swords": [
        "contemplation",
        "expansion",
        "healing",
        "meditation",
        "outcome",
        "peace",
        "possession",
        "protection",
        "recovery",
        "recuperation",
        "reflection",
        "relaxation",
        "rest",
        "retirement",
        "retreat",
        "sleep",
        "solitude",
        "stability",
        "truce",
        "wait",
    ],
    "5 of Swords": [
        "adversity",
        "challenge",
        "change",
        "competition",
        "conflict",
        "confrontation",
        "cowardice",
        "cruelty",
        "defeat",
        "degradation",
        "difficulty",
        "disgrace",
        "disruption",
        "domination",
        "drama",
        "ego",
        "exile",
        "failure",
        "loss",
        "power",
        "restriction",
        "retribution",
        "sadness",
        "slander",
        "tension",
        "uncertainty",
        "unfairness",
        "weakness",
    ],
    "6 of Swords": [
        "balance",
        "change",
        "curiosity",
        "emotional",
        "exploration",
        "flux",
        "growth",
        "illumination",
        "journey",
        "movement",
        "moving on",
        "obstacle",
        "peace",
        "reasoning",
        "recovery",
        "speed",
        "transfer",
        "transition",
        "traveling",
    ],
    "7 of Swords": [
        "attempt",
        "betrayal",
        "challenge",
        "confidentiality",
        "creativity",
        "deception",
        "defeat",
        "dishonesty",
        "faith",
        "gossip",
        "guilt",
        "hidden",
        "loss",
        "plan",
        "secret",
        "secrets",
        "sneakiness",
        "stealth",
        "theft",
        "willpower",
    ],
    "8 of Swords": [
        "betrayal",
        "bondage",
        "censorship",
        "change",
        "confusion",
        "entrapment",
        "fear",
        "imprisonment",
        "isolation",
        "laziness",
        "limitation",
        "logic",
        "obstacle",
        "powerlessness",
        "progress",
        "restriction",
        "strength",
        "stunned",
    ],
    "9 of Swords": [
        "anxiety",
        "concern",
        "crisis",
        "deceit",
        "despair",
        "difficulty",
        "disappointment",
        "distress",
        "doubt",
        "fears",
        "fruition",
        "fulfillment",
        "guilt",
        "loss",
        "nightmare",
        "nightmares",
        "overwhelming",
        "potential",
        "regret",
        "sadness",
        "sleeplessness",
        "stress",
        "suffering",
        "transformation",
        "uncertainty",
        "worries",
        "worry",
    ],
    "10 of Swords": [
        "betrayal",
        "blockage",
        "completion",
        "crisis",
        "culmination",
        "defeat",
        "destruction",
        "disaster",
        "ending",
        "endings",
        "failure",
        "fear",
        "manifestation",
        "obsession",
        "pain",
        "painful",
        "release",
        "sacrifice",
        "sadness",
        "suffering",
    ],
    "Page of Swords": [
        "aggression",
        "anger",
        "attention",
        "calculation",
        "cleverness",
        "communication",
        "curiosity",
        "dexterity",
        "energy",
        "inquisitiveness",
        "intelligence",
        "investigation",
        "learning",
        "vigilant",
    ],
    "Knight of Swords": [
        "action",
        "ambition",
        "anger",
        "courage",
        "determination",
        "drive",
        "extreme",
        "focus",
        "formation",
        "haste",
        "hostility",
        "impatience",
        "impetuous",
        "movement",
        "opportunity",
        "power",
        "rebel",
        "swift",
        "temperamental",
        "violence",
        "warrior",
    ],
    "Queen of Swords": [
        "clarity",
        "concept",
        "decision",
        "directness",
        "discriminating",
        "fairness",
        "honesty",
        "independence",
        "influence",
        "intellect",
        "logic",
        "organization",
        "perception",
        "power",
        "pretentious",
        "rigorous",
        "satisfaction",
        "strength",
        "wisdom",
    ],
    "King of Swords": [
        "analysis",
        "articulation",
        "authority",
        "calm",
        "creative urge",
        "diplomacy",
        "focus",
        "guidance",
        "impartiality",
        "integrity",
        "intellect",
        "judgment",
        "justice",
        "leadership",
        "logic",
        "order",
        "power",
        "precision",
        "rationality",
        "stability",
        "tact",
        "truth",
    ],
    "Ace of Pentacles": [
        "abundance",
        "beginning",
        "beginnings",
        "creative urge",
        "fortune",
        "gain",
        "gift",
        "inspiration",
        "manifestation",
        "material",
        "materialism",
        "opportunity",
        "physical world",
        "potential",
        "presence",
        "prosperity",
        "success",
        "wealth",
    ],
    "2 of Pentacles": [
        "adaptability",
        "balance",
        "choice",
        "choices",
        "dance",
        "decision",
        "dexterity",
        "division",
        "duality",
        "financial",
        "flexibility",
        "force",
        "joy",
        "juggling",
        "multitasking",
        "prioritization",
    ],
    "3 of Pentacles": [
        "art",
        "collaboration",
        "community",
        "concept",
        "consulting",
        "cooperation",
        "craftsmanship",
        "creativity",
        "effort",
        "flux",
        "inspiration",
        "installation",
        "outcome",
        "project",
        "recognition",
        "skill",
        "talent",
        "teamwork",
        "trade",
        "work",
    ],
    "4 of Pentacles": [
        "concentration",
        "conservation",
        "control",
        "determination",
        "expansion",
        "gain",
        "greed",
        "hardy",
        "hoarding",
        "inheritance",
        "investment",
        "outcome",
        "possession",
        "possessive",
        "possessiveness",
        "realization",
        "savings",
        "security",
        "selfishness",
        "stability",
        "stagnant",
        "thrift",
    ],
    "5 of Pentacles": [
        "adversity",
        "challenge",
        "challenges",
        "change",
        "cold",
        "dark",
        "despair",
        "financial",
        "hardship",
        "insecurity",
        "isolation",
        "lack",
        "loss",
        "need",
        "obstacle",
        "poverty",
        "rejection",
        "restriction",
        "sadness",
        "struggle",
        "victim",
        "waste",
        "yearning",
    ],
    "6 of Pentacles": [
        "altruism",
        "balance",
        "charity",
        "comfort",
        "distribution",
        "fairness",
        "gain",
        "generosity",
        "gift",
        "giving",
        "growth",
        "help",
        "illumination",
        "journey",
        "justice",
        "mercy",
        "offer",
        "sharing",
        "success",
        "support",
        "sympathy",
        "wealth",
    ],
    "7 of Pentacles": [
        "accomplishment",
        "assessment",
        "business",
        "challenge",
        "charity",
        "checking",
        "contemplation",
        "counting",
        "creativity",
        "deal",
        "development",
        "exchange",
        "expansion",
        "faith",
        "flowering",
        "growth",
        "harvest",
        "investment",
        "patience",
        "planning",
        "reflection",
        "ripening",
        "waiting",
        "willpower",
    ],
    "8 of Pentacles": [
        "autonomy",
        "change",
        "commitment",
        "craftsmanship",
        "dedication",
        "detail",
        "dexterity",
        "diligence",
        "finesse",
        "habit",
        "hard work",
        "improvement",
        "learning",
        "logic",
        "proficiency",
        "progress",
        "refinement",
        "repetitive",
        "routine",
        "skill",
        "strength",
        "technique",
    ],
    "9 of Pentacles": [
        "abundance",
        "accomplishment",
        "contentment",
        "discernment",
        "elegance",
        "enjoyment",
        "fruition",
        "fulfillment",
        "gratitude",
        "independence",
        "investment",
        "joy",
        "luxury",
        "potential",
        "project",
        "prosperity",
        "prudence",
        "refinement",
        "safety",
        "self-reliance",
        "self-sufficiency",
        "transformation",
    ],
    "10 of Pentacles": [
        "completion",
        "culmination",
        "ending",
        "family",
        "home",
        "inheritance",
        "legacy",
        "manifestation",
        "materialism",
        "prosperity",
        "safety",
        "security",
        "tradition",
        "treasure",
        "wealth",
    ],
    "Page of Pentacles": [
        "ambition",
        "apprenticeship",
        "certainty",
        "curiosity",
        "dependable",
        "focus",
        "health",
        "inspiration",
        "learning",
        "potential",
        "practicality",
        "presence",
        "responsibility",
        "stability",
        "studies",
    ],
    "Knight of Pentacles": [
        "action",
        "delusion",
        "determination",
        "discipline",
        "efficiency",
        "formation",
        "hard work",
        "irrationality",
        "irresponsibility",
        "materialism",
        "opportunity",
        "patience",
        "practicality",
        "reliability",
        "responsibility",
        "wealth",
    ],
    "Queen of Pentacles": [
        "abundance",
        "capability",
        "care",
        "caretaker",
        "comfort",
        "compassion",
        "concept",
        "conservation",
        "generosity",
        "influence",
        "maternal",
        "nurturing",
        "organization",
        "practicality",
        "protection",
        "rationality",
        "satisfaction",
        "security",
        "sensuality",
        "warmth",
        "wealth",
    ],
    "King of Pentacles": [
        "abundance",
        "ambition",
        "authority",
        "business",
        "creative urge",
        "dependable",
        "discipline",
        "enterprising",
        "entrepreneur",
        "financial",
        "materialism",
        "practicality",
        "prosperity",
        "rationality",
        "responsibility",
        "security",
        "stability",
        "success",
        "wealth",
    ],
};

const allSuitWords = {
    Pentacles: ["health", "wealth"],
    Swords: ["learning", "logic"],
    Cups: ["connection", "emotion"],
    Wands: ["creativity", "passion"],
};

function getRankWords(rank, isReversed) {
    const cards = Object.entries(allCards)
        .filter(([cardName]) => cardName.includes(rank))
        .map(([cardName, words]) =>
            isReversed ? getCardOpposites(cardName) : words
        );
    return [
        ...new Set(
            cards
                .map((words) =>
                    words.filter((word) =>
                        cards.every((ws) => ws.includes(word))
                    )
                )
                .flat(Infinity)
        ),
    ].sort();
}

function getCardOpposites(name) {
    return [
        ...new Set(allCards[name].map(getOppositeWords).flat(Infinity)),
    ].sort();
}

function getOppositeWords(word) {
    return opposites
        .filter((pair) => pair.includes(word))
        .map((pair) => pair[pair.indexOf(word) ? 0 : 1])
        .filter(Boolean); // in case empty string in pair
}

export {
    allCards,
    opposites,
    allSuitWords,
    getRankWords,
    getCardOpposites,
    getOppositeWords,
};
