/*

OPENAI CHATGPT PROMPTS:

Please flatten and alphabetize the following array, then display it
in plain text:
* flatten opposites, then in new chat window paste flat list

...

I would like you to go through each tarot card in the major arcana.
Using ONLY the provided list, go through each word and filter out any
that do not apply to the current card. Take the remaining words and
assign them as an array to the card's name in a JSON object. Do not
use the word "The" or any numbers in the card's name. It is important
that each array only has words from the provided list. Please do not
provide any synonyms, do not change the word's grammar or tense, and
do not draw words for the cards from other sources.

...

Remember, by provided list I mean the list I first pasted into the chat.
You seem to be straying from the list. Please only use those words, and
no synonyms. Give it another try.

...

Can you do the same thing for the [SUIT] suit of the minor arcana?
Please write the card names with digits instead of spelling out numbers.

...

* I ended up with words from outside the list on my final try, but I
* don't mind it. I think they work, and each card should have at least
* a few words from the opposites list. Lesson: Chat GPT can be finicky.

*/

const opposites = [
    ["abundance", "scarcity"],
    ["acceleration", ""],
    ["action", "inaction"],
    ["adaptability", ""],
    ["ambition", "complacency"],
    ["anxiety", "contentment"],
    ["balance", "imbalance"],
    ["beginnings", "endings"],
    ["betrayal", "loyalty"],
    ["bondage", "freedom"],
    ["boundaries", "unrestricted"],
    ["breakthrough", "stagnation"],
    ["burden", "lightness"],
    ["celebration", "mourning"],
    ["charisma", "dullness"],
    ["charm", "repulsion"],
    ["challenges", "ease"],
    ["change", "stability"],
    ["charming", "repulsive"],
    ["clarity", "confusion"],
    ["collaboration", "solitude"],
    ["complacency", "ambition"],
    ["compassion", "cruelty"],
    ["completion", "incompletion"],
    ["conflict", "agreement"],
    ["confusion", "clarity"],
    ["conformity", "rebellion"],
    ["connection", "disconnection"],
    ["contentment", "dissatisfaction"],
    ["control", "chaos"],
    ["cooperation", "competition"],
    ["courage", "fear"],
    ["creative", "uncreative"],
    ["creativity", "uncreativity"],
    ["curiosity", "apathy"],
    ["deadlock", "movement"],
    ["deception", "honesty"],
    ["departure", "arrival"],
    ["desire", "disinterest"],
    ["desengagement", "engagement"],
    ["destiny", "randomness"],
    ["determination", "hesitation"],
    ["direct", "indirect"],
    ["diligence", "neglect"],
    ["disappointment", "satisfaction"],
    ["dishonesty", "honesty"],
    ["dreams", "reality"],
    ["effort", "ease"],
    ["emotion", "apathy"],
    ["emotional", "unemotional"],
    ["equity", "injustice"],
    ["expansion", "contraction"],
    ["fairness", "unfairness"],
    ["fate", "free will"],
    ["feeling", "numbness"],
    ["flexibility", "rigidity"],
    ["foresight", "blindness"],
    ["fortitude", "weakness"],
    ["fulfillment", "emptiness"],
    ["generosity", "selfishness"],
    ["greed", "generosity"],
    ["grief", "happiness"],
    ["guidance", "confusion"],
    ["hardship", "ease"],
    ["harmony", "discord"],
    ["healing", "hurt"],
    ["heartbreak", "happiness"],
    ["happiness", "sadness"],
    ["harmony", "dissonance"],
    ["illusion", "reality"],
    ["imprisonment", "freedom"],
    ["inaction", "action"],
    ["independence", "dependence"],
    ["indifference", "interest"],
    ["individuality", "conformity"],
    ["inquiry", "ignorance"],
    ["inspiration", "uninspired"],
    ["intuition", "reason"],
    ["isolation", "togetherness"],
    ["joy", "sorrow"],
    ["journey", "staying put"],
    ["leadership", "followership"],
    ["love", "hatred"],
    ["luck", "misfortune"],
    ["mastery", "incompetence"],
    ["materialism", "spirituality"],
    ["mystery", "clarity"],
    ["new", "old"],
    ["nostalgia", "forward-looking"],
    ["nurturing", "neglect"],
    ["passion", "indifference"],
    ["patience", "impatience"],
    ["perspective", "narrowness"],
    ["planning", "improvisation"],
    ["possessiveness", "generosity"],
    ["power", "weakness"],
    ["prosperity", "poverty"],
    ["recognition", "obscurity"],
    ["recovery", "illness"],
    ["renewal", "deterioration"],
    ["resilience", "fragility"],
    ["responsibility", "carelessness"],
    ["revelation", "secrecy"],
    ["risk", "safety"],
    ["sadness", "happiness"],
    ["secrets", "transparency"],
    ["security", "insecurity"],
    ["self-confidence", "self-doubt"],
    ["self-sufficiency", "dependency"],
    ["sensuality", "frigidity"],
    ["shock", "calm"],
    ["solitude", "companionship"],
    ["spontaneity", "predictability"],
    ["stagnation", "movement"],
    ["success", "failure"],
    ["surrender", "resistance"],
    ["temptation", "resistance"],
    ["tradition", "innovation"],
    ["transformation", "stagnation"],
    ["truth", "falsehood"],
    ["unity", "division"],
    ["upheaval", "stability"],
    ["victory", "defeat"],
    ["vitality", "lethargy"],
    ["waiting", "action"],
    ["wealth", "poverty"],
    ["withdrawal", "engagement"],
    ["worry", "tranquility"],
];

const cards = {
    Fool: [
        "beginnings",
        "creativity",
        "curiosity",
        "innovation",
        "spontaneity",
        "freedom",
    ],
    Magician: [
        "action",
        "adaption",
        "creative",
        "innovation",
        "inspiration",
        "power",
        "transformation",
    ],
    "High Priestess": [
        "intuition",
        "mystery",
        "secrets",
        "solitude",
        "tranquility",
        "reflection",
        "secrecy",
    ],
    Empress: [
        "abundance",
        "nurturing",
        "gentleness",
        "love",
        "beauty",
        "fertility",
        "creativity",
    ],
    Emperor: [
        "leadership",
        "power",
        "authority",
        "stability",
        "control",
        "strength",
        "determination",
    ],
    Hierophant: [
        "tradition",
        "conformity",
        "guidance",
        "unity",
        "spirituality",
        "teaching",
        "knowledge",
    ],
    Lovers: [
        "love",
        "connection",
        "relationship",
        "passion",
        "choice",
        "desire",
        "harmony",
    ],
    Chariot: [
        "determination",
        "willpower",
        "victory",
        "movement",
        "control",
        "courage",
        "success",
    ],
    Strength: [
        "strength",
        "courage",
        "gentleness",
        "power",
        "vitality",
        "determination",
        "caring",
    ],
    Hermit: [
        "solitude",
        "reflection",
        "introspection",
        "wisdom",
        "isolation",
        "guidance",
        "patience",
    ],
    "Wheel of Fortune": [
        "change",
        "luck",
        "fate",
        "randomness",
        "movement",
        "transition",
        "opportunity",
    ],
    Justice: [
        "fairness",
        "equity",
        "truth",
        "balance",
        "reflection",
        "honesty",
        "clarity",
    ],
    "Hanged Man": [
        "surrender",
        "transformation",
        "reflection",
        "perspective",
        "change",
        "sacrifice",
        "waiting",
    ],
    Death: [
        "transformation",
        "endings",
        "change",
        "renewal",
        "transition",
        "release",
        "mystery",
    ],
    Temperance: [
        "balance",
        "harmony",
        "adaptability",
        "moderation",
        "patience",
        "healing",
        "integration",
    ],
    Devil: [
        "temptation",
        "bondage",
        "materialism",
        "selfishness",
        "greed",
        "illusion",
        "desire",
    ],
    Tower: [
        "upheaval",
        "change",
        "disruption",
        "transformation",
        "crisis",
        "revelation",
        "chaos",
    ],
    Star: [
        "hope",
        "inspiration",
        "healing",
        "guidance",
        "clarity",
        "reflection",
        "vitality",
    ],
    Moon: [
        "illusion",
        "confusion",
        "intuition",
        "mystery",
        "reflection",
        "emotional",
        "secrets",
    ],
    Sun: [
        "happiness",
        "joy",
        "clarity",
        "vitality",
        "success",
        "celebration",
        "positivity",
    ],
    Judgment: [
        "reflection",
        "renewal",
        "transformation",
        "recognition",
        "revelation",
        "awakening",
        "forgiveness",
    ],
    World: [
        "completion",
        "fulfillment",
        "achievement",
        "wholeness",
        "unity",
        "success",
        "integration",
    ],
    "Ace of Wands": [
        "beginnings",
        "creativity",
        "inspiration",
        "passion",
        "desire",
        "potential",
        "energy",
    ],
    "2 of Wands": [
        "planning",
        "foresight",
        "ambition",
        "exploration",
        "choice",
        "direction",
        "decision",
    ],
    "3 of Wands": [
        "expansion",
        "growth",
        "optimism",
        "foresight",
        "preparation",
        "prosperity",
        "opportunity",
    ],
    "4 of Wands": [
        "celebration",
        "harmony",
        "completion",
        "happiness",
        "unity",
        "joy",
        "achievement",
    ],
    "5 of Wands": [
        "conflict",
        "competition",
        "struggle",
        "chaos",
        "challenge",
        "effort",
        "action",
    ],
    "6 of Wands": [
        "victory",
        "success",
        "recognition",
        "achievement",
        "triumph",
        "pride",
        "confidence",
    ],
    "7 of Wands": [
        "courage",
        "determination",
        "defense",
        "resistance",
        "fight",
        "confidence",
        "challenges",
    ],
    "8 of Wands": [
        "movement",
        "speed",
        "action",
        "progress",
        "change",
        "travel",
        "communication",
    ],
    "9 of Wands": [
        "resilience",
        "perseverance",
        "endurance",
        "defense",
        "strength",
        "determination",
        "caution",
    ],
    "10 of Wands": [
        "burden",
        "responsibility",
        "overwhelm",
        "hard work",
        "pressure",
        "struggle",
        "challenge",
    ],
    "Page of Wands": [
        "curiosity",
        "enthusiasm",
        "exploration",
        "learning",
        "creativity",
        "inspiration",
        "adventure",
    ],
    "Knight of Wands": [
        "action",
        "adventure",
        "daring",
        "enthusiasm",
        "travel",
        "courage",
        "ambition",
    ],
    "Queen of Wands": [
        "confidence",
        "leadership",
        "charisma",
        "determination",
        "passion",
        "strength",
        "independence",
    ],
    "King of Wands": [
        "leadership",
        "confidence",
        "inspiration",
        "ambition",
        "vision",
        "strength",
        "assertiveness",
    ],
    "Ace of Cups": [
        "emotional",
        "beginnings",
        "love",
        "compassion",
        "intuition",
        "feeling",
        "healing",
    ],
    "2 of Cups": [
        "connection",
        "relationship",
        "partnership",
        "love",
        "harmony",
        "balance",
        "unity",
    ],
    "3 of Cups": [
        "celebration",
        "friendship",
        "joy",
        "happiness",
        "community",
        "gathering",
        "reunion",
    ],
    "4 of Cups": [
        "discontent",
        "introspection",
        "apathy",
        "reflection",
        "emotional",
        "boredom",
        "missed opportunities",
    ],
    "5 of Cups": [
        "loss",
        "grief",
        "sadness",
        "disappointment",
        "regret",
        "reflection",
        "emotional",
    ],
    "6 of Cups": [
        "nostalgia",
        "childhood",
        "memories",
        "innocence",
        "reminiscing",
        "past",
        "connection",
    ],
    "7 of Cups": [
        "illusion",
        "fantasy",
        "choices",
        "imagination",
        "confusion",
        "dreams",
        "temptation",
    ],
    "8 of Cups": [
        "departure",
        "journey",
        "search",
        "transition",
        "moving on",
        "exploration",
        "emotional",
    ],
    "9 of Cups": [
        "fulfillment",
        "satisfaction",
        "contentment",
        "happiness",
        "wish fulfillment",
        "joy",
        "abundance",
    ],
    "10 of Cups": [
        "happiness",
        "harmony",
        "family",
        "fulfillment",
        "joy",
        "emotional",
        "celebration",
    ],
    "Page of Cups": [
        "emotional",
        "intuition",
        "creativity",
        "sensitivity",
        "dreams",
        "curiosity",
        "compassion",
    ],
    "Knight of Cups": [
        "romance",
        "creativity",
        "emotional",
        "idealism",
        "dreamer",
        "compassion",
        "inspiration",
    ],
    "Queen of Cups": [
        "empathy",
        "compassion",
        "nurturing",
        "intuition",
        "emotional",
        "sensitivity",
        "love",
    ],
    "King of Cups": [
        "emotional",
        "balance",
        "compassion",
        "wisdom",
        "empathy",
        "leadership",
        "calmness",
    ],
    "Ace of Swords": [
        "clarity",
        "mental",
        "beginnings",
        "truth",
        "intellect",
        "insight",
        "focus",
    ],
    "2 of Swords": [
        "decision",
        "choices",
        "stalemate",
        "balance",
        "dilemma",
        "reflection",
        "indecision",
    ],
    "3 of Swords": [
        "heartbreak",
        "pain",
        "loss",
        "sorrow",
        "betrayal",
        "grief",
        "emotional",
    ],
    "4 of Swords": [
        "rest",
        "recovery",
        "healing",
        "meditation",
        "peace",
        "contemplation",
        "relaxation",
    ],
    "5 of Swords": [
        "conflict",
        "defeat",
        "competition",
        "loss",
        "confrontation",
        "ego",
        "disruption",
    ],
    "6 of Swords": [
        "transition",
        "moving on",
        "journey",
        "change",
        "emotional",
        "recovery",
        "peace",
    ],
    "7 of Swords": [
        "deception",
        "dishonesty",
        "theft",
        "sneakiness",
        "betrayal",
        "secrets",
        "guilt",
    ],
    "8 of Swords": [
        "restriction",
        "imprisonment",
        "entrapment",
        "fear",
        "limitation",
        "powerlessness",
        "confusion",
    ],
    "9 of Swords": [
        "anxiety",
        "worries",
        "fears",
        "nightmares",
        "stress",
        "guilt",
        "distress",
    ],
    "10 of Swords": [
        "endings",
        "painful",
        "completion",
        "betrayal",
        "suffering",
        "release",
        "destruction",
    ],
    "Page of Swords": [
        "curiosity",
        "intelligence",
        "communication",
        "inquisitiveness",
        "learning",
        "investigation",
        "cleverness",
    ],
    "Knight of Swords": [
        "action",
        "determination",
        "ambition",
        "courage",
        "drive",
        "focus",
        "swift",
    ],
    "Queen of Swords": [
        "clarity",
        "independence",
        "intellect",
        "strength",
        "wisdom",
        "honesty",
        "fairness",
    ],
    "King of Swords": [
        "authority",
        "rationality",
        "truth",
        "justice",
        "integrity",
        "leadership",
        "logic",
    ],
    "Ace of Pentacles": [
        "prosperity",
        "abundance",
        "beginnings",
        "material",
        "opportunity",
        "manifestation",
        "wealth",
    ],
    "2 of Pentacles": [
        "balance",
        "juggling",
        "choices",
        "adaptability",
        "financial",
        "prioritization",
        "multitasking",
    ],
    "3 of Pentacles": [
        "collaboration",
        "cooperation",
        "teamwork",
        "skill",
        "craftsmanship",
        "recognition",
        "effort",
    ],
    "4 of Pentacles": [
        "security",
        "stability",
        "conservation",
        "possession",
        "control",
        "greed",
        "hoarding",
    ],
    "5 of Pentacles": [
        "hardship",
        "poverty",
        "struggle",
        "isolation",
        "loss",
        "financial",
        "challenges",
    ],
    "6 of Pentacles": [
        "generosity",
        "charity",
        "giving",
        "sharing",
        "fairness",
        "help",
        "support",
    ],
    "7 of Pentacles": [
        "patience",
        "assessment",
        "reflection",
        "growth",
        "investment",
        "waiting",
        "harvest",
    ],
    "8 of Pentacles": [
        "diligence",
        "dedication",
        "hard work",
        "craftsmanship",
        "improvement",
        "skill",
        "detail",
    ],
    "9 of Pentacles": [
        "self-sufficiency",
        "independence",
        "luxury",
        "abundance",
        "enjoyment",
        "prosperity",
        "contentment",
    ],
    "10 of Pentacles": [
        "legacy",
        "wealth",
        "family",
        "tradition",
        "inheritance",
        "security",
        "prosperity",
    ],
    "Page of Pentacles": [
        "learning",
        "studies",
        "responsibility",
        "curiosity",
        "practicality",
        "ambition",
        "focus",
    ],
    "Knight of Pentacles": [
        "responsibility",
        "reliability",
        "practicality",
        "determination",
        "hard work",
        "patience",
        "discipline",
    ],
    "Queen of Pentacles": [
        "nurturing",
        "practicality",
        "abundance",
        "security",
        "compassion",
        "generosity",
        "caretaker",
    ],
    "King of Pentacles": [
        "prosperity",
        "abundance",
        "practicality",
        "stability",
        "financial",
        "success",
        "responsibility",
    ],
};

export { cards, opposites };
