const cards = {
    Fool: ["beginnings", "folly", "innocence", "optimism", "spontaneity"],
    Magician: [
        "creativity",
        "manifestation",
        "power",
        "skill",
        "transformation",
    ],
    "High Priestess": [
        "femininity",
        "intuition",
        "mystery",
        "secrets",
        "unconsciousness",
    ],
    Empress: [
        "abundance",
        "fertility",
        "motherhood",
        "nurturing",
        "sensuality",
    ],
    Emperor: ["ambition", "authority", "control", "leadership", "structure"],
    Hierophant: [
        "guidance",
        "morality",
        "religion",
        "spiritual growth",
        "tradition",
    ],
    Lovers: ["choices", "harmony", "love", "relationships", "union"],
    Chariot: ["control", "determination", "progress", "victory", "willpower"],
    Strength: [
        "compassion",
        "confidence",
        "courage",
        "inner strength",
        "patience",
    ],
    Hermit: ["guidance", "reflection", "self-discovery", "solitude", "wisdom"],
    "Wheel of Fortune": ["change", "cycles", "destiny", "fate", "luck"],
    Justice: [
        "accountability",
        "balance",
        "fairness",
        "legal matters",
        "truth",
    ],
    "Hanged Man": [
        "letting go",
        "perspective",
        "sacrifice",
        "surrender",
        "suspension",
    ],
    Death: ["change", "closure", "endings", "rebirth", "transformation"],
    Temperance: ["adaptation", "balance", "harmony", "healing", "moderation"],
    Devil: ["addiction", "bondage", "illusion", "materialism", "temptation"],
    Tower: ["chaos", "destruction", "revelation", "sudden change", "upheaval"],
    Star: ["aspiration", "enlightenment", "healing", "hope", "inspiration"],
    Moon: ["dreams", "emotions", "illusion", "intuition", "uncertainty"],
    Sun: ["abundance", "clarity", "joy", "success", "vitality"],
    Judgment: [
        "awakening",
        "judgment",
        "rebirth",
        "redemption",
        "transformation",
    ],
    World: [
        "achievement",
        "completion",
        "fulfillment",
        "integration",
        "wholeness",
    ],
    "Ace of Wands": [
        "creativity",
        "enthusiasm",
        "inspiration",
        "beginnings",
        "potential",
    ],
    "2 of Wands": [
        "ambition",
        "choices",
        "exploration",
        "partnership",
        "planning",
    ],
    "3 of Wands": [
        "anticipation",
        "confidence",
        "expansion",
        "exploration",
        "progress",
    ],
    "4 of Wands": [
        "celebration",
        "community",
        "harmony",
        "homecoming",
        "stability",
    ],
    "5 of Wands": [
        "challenge",
        "competition",
        "conflict",
        "disagreement",
        "struggle",
    ],
    "6 of Wands": [
        "confidence",
        "recognition",
        "success",
        "triumph",
        "victory",
    ],
    "7 of Wands": [
        "courage",
        "defense",
        "determination",
        "persistence",
        "resilience",
    ],
    "8 of Wands": [
        "communication",
        "expansion",
        "movement",
        "progress",
        "swiftness",
    ],
    "9 of Wands": [
        "endurance",
        "perseverance",
        "resilience",
        "strength",
        "vigilance",
    ],
    "10 of Wands": [
        "burden",
        "hard work",
        "overwhelm",
        "responsibility",
        "struggle",
    ],
    "Page of Wands": [
        "creative energy",
        "curiosity",
        "enthusiasm",
        "exploration",
        "new opportunities",
    ],
    "Knight of Wands": [
        "action",
        "adventure",
        "boldness",
        "determination",
        "passion",
    ],
    "Queen of Wands": [
        "charisma",
        "confidence",
        "energy",
        "independence",
        "leadership",
    ],
    "King of Wands": [
        "authority",
        "inspiration",
        "leadership",
        "strength",
        "vision",
    ],
    "Ace of Cups": [
        "affection",
        "beginnings",
        "connection",
        "emotions",
        "intuition",
        "love",
    ],
    "2 of Cups": ["harmony", "love", "partnership", "relationship", "union"],
    "3 of Cups": ["abundance", "celebration", "friendship", "gathering", "joy"],
    "4 of Cups": [
        "apathy",
        "boredom",
        "discontent",
        "opportunity",
        "reflection",
    ],
    "5 of Cups": ["despair", "grief", "loss", "regret", "sorrow"],
    "6 of Cups": [
        "childhood",
        "innocence",
        "memories",
        "nostalgia",
        "sweetness",
    ],
    "7 of Cups": ["choices", "confusion", "dreams", "fantasy", "illusion"],
    "8 of Cups": [
        "abandonment",
        "exploration",
        "journey",
        "quest",
        "transition",
    ],
    "9 of Cups": [
        "contentment",
        "fulfillment",
        "gratitude",
        "satisfaction",
        "wishes",
    ],
    "10 of Cups": ["family", "fulfillment", "happiness", "harmony", "joy"],
    "Page of Cups": [
        "creativity",
        "dreams",
        "imagination",
        "intuition",
        "sensitivity",
    ],
    "Knight of Cups": ["chivalry", "dreamer", "emotion", "passion", "romance"],
    "Queen of Cups": [
        "compassion",
        "empathy",
        "intuition",
        "nurturing",
        "sensitivity",
    ],
    "King of Cups": [
        "composure",
        "emotional control",
        "empathy",
        "stability",
        "wisdom",
    ],
    "Ace of Swords": [
        "beginnings",
        "clarity",
        "insight",
        "intellect",
        "justice",
        "truth",
    ],
    "2 of Swords": ["balance", "conflict", "decision", "dilemma", "stalemate"],
    "3 of Swords": ["betrayal", "grief", "heartache", "loss", "sorrow"],
    "4 of Swords": ["healing", "meditation", "recovery", "rest", "retreat"],
    "5 of Swords": ["conflict", "confrontation", "defeat", "hostility", "loss"],
    "6 of Swords": [
        "healing",
        "journey",
        "moving on",
        "progress",
        "transition",
    ],
    "7 of Swords": [
        "betrayal",
        "deception",
        "secrecy",
        "sneakiness",
        "stealth",
    ],
    "8 of Swords": [
        "feeling trapped",
        "helplessness",
        "isolation",
        "limitation",
        "restriction",
    ],
    "9 of Swords": ["anxiety", "fear", "guilt", "nightmares", "worry"],
    "10 of Swords": ["betrayal", "crisis", "endings", "pain", "suffering"],
    "Page of Swords": [
        "alertness",
        "communication",
        "curiosity",
        "inquisitiveness",
        "intellect",
    ],
    "Knight of Swords": [
        "action",
        "ambition",
        "challenges",
        "determination",
        "intelligence",
    ],
    "Queen of Swords": [
        "clarity",
        "independence",
        "intellect",
        "logic",
        "skepticism",
    ],
    "King of Swords": [
        "authority",
        "fairness",
        "intelligence",
        "justice",
        "wisdom",
    ],
    "Ace of Pentacles": [
        "abundance",
        "beginnings",
        "manifestation",
        "opportunity",
        "prosperity",
        "wealth",
    ],
    "2 of Pentacles": [
        "adaptability",
        "balance",
        "choices",
        "flexibility",
        "juggling",
    ],
    "3 of Pentacles": [
        "achievement",
        "collaboration",
        "cooperation",
        "skill",
        "teamwork",
    ],
    "4 of Pentacles": [
        "conservatism",
        "holding on",
        "possession",
        "security",
        "stability",
    ],
    "5 of Pentacles": [
        "desperation",
        "hardship",
        "isolation",
        "poverty",
        "struggle",
    ],
    "6 of Pentacles": [
        "abundance",
        "charity",
        "fairness",
        "generosity",
        "sharing",
    ],
    "7 of Pentacles": [
        "assessment",
        "growth",
        "harvest",
        "patience",
        "reflection",
    ],
    "8 of Pentacles": [
        "craftsmanship",
        "diligence",
        "hard work",
        "precision",
        "skill development",
    ],
    "9 of Pentacles": [
        "aptitude",
        "independence",
        "luxury",
        "security",
        "self-sufficiency",
    ],
    "10 of Pentacles": [
        "family",
        "legacy",
        "prosperity",
        "tradition",
        "wealth",
    ],
    "Page of Pentacles": [
        "exploration",
        "learning",
        "practicality",
        "responsibility",
        "studiousness",
    ],
    "Knight of Pentacles": [
        "dependability",
        "efficiency",
        "practicality",
        "responsibility",
        "steadfastness",
    ],
    "Queen of Pentacles": [
        "abundance",
        "compassion",
        "nurturing",
        "practicality",
        "sustainability",
    ],
    "King of Pentacles": [
        "leadership",
        "prosperity",
        "security",
        "stability",
        "wealth",
    ],
};

export default cards;
